### ISSUE TITLE
冒昧的问一句， 当前的项目貌似并没有用到casbin

### ISSUE THREAD

**Issue by hzjsea** [KU4NG/go-admin-api-example#1]
另外可以在启动的时候加一个数据库检测

// 检查数据库是否存在 不存在则创建数据库
func CheckWithDb(dsn string) error{
    dsn = fmt.Sprintf("%s:%s@tcp(%s:%d)/", common.Conf.Mysql.Username, common.Conf.Mysql.Password, common.Conf.Mysql.Host, common.Conf.Mysql.Port)
    log.Println(dsn)
    db, err := sql.Open("mysql", dsn)
    if err != nil{
        fmt.Println("open sql error")
    }
    defer db.Close()
    query := fmt.Sprintf("CREATE DATABASE IF NOT EXISTS `%s` DEFAULT CHARACTER SET = `utf8mb4`;",common.Conf.Mysql.Database)
    _, err = db.Exec(query)
    return err
}

**Comment by KU4NG** [comment]
还没有写到 casbin，我也是才用 go，很多都得慢慢的抄和改，所以有点慢。另外就是检测数据库这个意义不大，不建议自动创建，毕竟这不是那种提供初始化页面的平台，如果想实现那种功能自己扩充下。

**Comment by hsluoyz** [comment]
需要casbin +1

**Comment by hzjsea** [comment]
> 还没有写到casbin，我也是才去，很多人都得慢慢用抄和改，所以自动有点慢。另外就是检测这个意义不大，不建议创建，毕竟这不是那个提供数据库初始化页面的平台，如果想实现自己的功能扩展下。
嗯呢，期待casbin的内容

**Comment by hzjsea** [comment]
> 还没有写到casbin，我也是才去，很多人都得慢慢用抄和改，所以自动有点慢。另外就是检测这个意义不大，不建议创建，毕竟这不是那个提供数据库初始化页面的平台，如果想实现自己的功能扩展下。

嗯呢， 期待casbin
